In [28]:
# import modules

import os

import numpy as np
import pandas as pd

from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV

project_dir = os.path.abspath('..')
data_dir = os.path.join(project_dir, 'data')
subs_dir = os.path.join(project_dir, 'subs')

In [6]:
# load train-test
train = pd.read_csv(os.path.join(data_dir, 'train.csv'))
test = pd.read_csv(os.path.join(data_dir, 'test.csv'))

## Visualize data

In [7]:
train.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,39205.170000,0
1,3,2,34,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,49278.030000,0
2,4,2,23,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,67333.770000,0
3,8,2,37,0,195,195,0,0,0,0,...,0,0,0,0,0,0,0,0,64007.970000,0
4,10,2,39,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0

In [8]:
train.count()

ID                               76020
var3                             76020
var15                            76020
imp_ent_var16_ult1               76020
imp_op_var39_comer_ult1          76020
imp_op_var39_comer_ult3          76020
imp_op_var40_comer_ult1          76020
imp_op_var40_comer_ult3          76020
imp_op_var40_efect_ult1          76020
imp_op_var40_efect_ult3          76020
imp_op_var40_ult1                76020
imp_op_var41_comer_ult1          76020
imp_op_var41_comer_ult3          76020
imp_op_var41_efect_ult1          76020
imp_op_var41_efect_ult3          76020
imp_op_var41_ult1                76020
imp_op_var39_efect_ult1          76020
imp_op_var39_efect_ult3          76020
imp_op_var39_ult1                76020
imp_sal_var16_ult1               76020
ind_var1_0                       76020
ind_var1                         76020
ind_var2_0                       76020
ind_var2                         76020
ind_var5_0                       76020
ind_var5                         76020
ind_var6_0                       76020
ind_var6                         76020
ind_var8_0                       76020
ind_var8                         76020
                                 ...
saldo_medio_var13_corto_hace2    76020
saldo_medio_var13_corto_hace3    76020
saldo_medio_var13_corto_ult1     76020
saldo_medio_var13_corto_ult3     76020
saldo_medio_var13_largo_hace2    76020
saldo_medio_var13_largo_hace3    76020
saldo_medio_var13_largo_ult1     76020
saldo_medio_var13_largo_ult3     76020
saldo_medio_var13_medio_hace2    76020
saldo_medio_var13_medio_hace3    76020
saldo_medio_var13_medio_ult1     76020
saldo_medio_var13_medio_ult3     76020
saldo_medio_var17_hace2          76020
saldo_medio_var17_hace3          76020
saldo_medio_var17_ult1           76020
saldo_medio_var17_ult3           76020
saldo_medio_var29_hace2          76020
saldo_medio_var29_hace3          76020
saldo_medio_var29_ult1           76020
saldo_medio_var29_ult3           76020
saldo_medio_var33_hace2          76020
saldo_medio_var33_hace3          76020
saldo_medio_var33_ult1           76020
saldo_medio_var33_ult3           76020
saldo_medio_var44_hace2          76020
saldo_medio_var44_hace3          76020
saldo_medio_var44_ult1           76020
saldo_medio_var44_ult3           76020
var38                            76020
TARGET                           76020
dtype: int64

In [9]:
train.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,117235.809430,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,182664.598503,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5163.750000,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67870.612500,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,106409.160000,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,118756.252500,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,22034738.760000,1.000000

In [12]:
train.dtypes

ID                                 int64
var3                               int64
var15                              int64
imp_ent_var16_ult1               float64
imp_op_var39_comer_ult1          float64
imp_op_var39_comer_ult3          float64
imp_op_var40_comer_ult1          float64
imp_op_var40_comer_ult3          float64
imp_op_var40_efect_ult1          float64
imp_op_var40_efect_ult3          float64
imp_op_var40_ult1                float64
imp_op_var41_comer_ult1          float64
imp_op_var41_comer_ult3          float64
imp_op_var41_efect_ult1          float64
imp_op_var41_efect_ult3          float64
imp_op_var41_ult1                float64
imp_op_var39_efect_ult1          float64
imp_op_var39_efect_ult3          float64
imp_op_var39_ult1                float64
imp_sal_var16_ult1               float64
ind_var1_0                         int64
ind_var1                           int64
ind_var2_0                         int64
ind_var2                           int64
ind_var5_0                         int64
ind_var5                           int64
ind_var6_0                         int64
ind_var6                           int64
ind_var8_0                         int64
ind_var8                           int64
                                  ...
saldo_medio_var13_corto_hace2    float64
saldo_medio_var13_corto_hace3    float64
saldo_medio_var13_corto_ult1     float64
saldo_medio_var13_corto_ult3     float64
saldo_medio_var13_largo_hace2    float64
saldo_medio_var13_largo_hace3    float64
saldo_medio_var13_largo_ult1     float64
saldo_medio_var13_largo_ult3     float64
saldo_medio_var13_medio_hace2    float64
saldo_medio_var13_medio_hace3      int64
saldo_medio_var13_medio_ult1       int64
saldo_medio_var13_medio_ult3     float64
saldo_medio_var17_hace2          float64
saldo_medio_var17_hace3          float64
saldo_medio_var17_ult1           float64
saldo_medio_var17_ult3           float64
saldo_medio_var29_hace2          float64
saldo_medio_var29_hace3          float64
saldo_medio_var29_ult1           float64
saldo_medio_var29_ult3           float64
saldo_medio_var33_hace2          float64
saldo_medio_var33_hace3          float64
saldo_medio_var33_ult1           float64
saldo_medio_var33_ult3           float64
saldo_medio_var44_hace2          float64
saldo_medio_var44_hace3          float64
saldo_medio_var44_ult1           float64
saldo_medio_var44_ult3           float64
var38                            float64
TARGET                             int64
dtype: object

In [13]:
test.count()

ID                               75818
var3                             75818
var15                            75818
imp_ent_var16_ult1               75818
imp_op_var39_comer_ult1          75818
imp_op_var39_comer_ult3          75818
imp_op_var40_comer_ult1          75818
imp_op_var40_comer_ult3          75818
imp_op_var40_efect_ult1          75818
imp_op_var40_efect_ult3          75818
imp_op_var40_ult1                75818
imp_op_var41_comer_ult1          75818
imp_op_var41_comer_ult3          75818
imp_op_var41_efect_ult1          75818
imp_op_var41_efect_ult3          75818
imp_op_var41_ult1                75818
imp_op_var39_efect_ult1          75818
imp_op_var39_efect_ult3          75818
imp_op_var39_ult1                75818
imp_sal_var16_ult1               75818
ind_var1_0                       75818
ind_var1                         75818
ind_var2_0                       75818
ind_var2                         75818
ind_var5_0                       75818
ind_var5                         75818
ind_var6_0                       75818
ind_var6                         75818
ind_var8_0                       75818
ind_var8                         75818
                                 ...
saldo_medio_var12_ult3           75818
saldo_medio_var13_corto_hace2    75818
saldo_medio_var13_corto_hace3    75818
saldo_medio_var13_corto_ult1     75818
saldo_medio_var13_corto_ult3     75818
saldo_medio_var13_largo_hace2    75818
saldo_medio_var13_largo_hace3    75818
saldo_medio_var13_largo_ult1     75818
saldo_medio_var13_largo_ult3     75818
saldo_medio_var13_medio_hace2    75818
saldo_medio_var13_medio_hace3    75818
saldo_medio_var13_medio_ult1     75818
saldo_medio_var13_medio_ult3     75818
saldo_medio_var17_hace2          75818
saldo_medio_var17_hace3          75818
saldo_medio_var17_ult1           75818
saldo_medio_var17_ult3           75818
saldo_medio_var29_hace2          75818
saldo_medio_var29_hace3          75818
saldo_medio_var29_ult1           75818
saldo_medio_var29_ult3           75818
saldo_medio_var33_hace2          75818
saldo_medio_var33_hace3          75818
saldo_medio_var33_ult1           75818
saldo_medio_var33_ult3           75818
saldo_medio_var44_hace2          75818
saldo_medio_var44_hace3          75818
saldo_medio_var44_ult1           75818
saldo_medio_var44_ult3           75818
var38                            75818
dtype: int64

In [15]:
# set data for train-test
data_x = train.ix[:, (train.columns != 'TARGET') & (train.columns != 'ID')].values
data_y = train.TARGET.values

data_x_test = test.ix[:, test.columns != 'ID'].values

In [29]:
# set model
clf1 = RandomForestClassifier(n_jobs=3, n_estimators=100)
cccv1 = CalibratedClassifierCV(clf1, method = 'isotonic', cv = 5)

In [30]:
# rmf_cv with 100 trees
cross_val_score(cccv1, data_x, data_y, cv = 5)

array([ 0.96040776,  0.96040776,  0.96040516,  0.96046833,  0.96046833])

In [31]:
# train and predict
cccv1.fit(data_x, data_y);
pred = cccv1.predict_proba(data_x_test)

In [34]:
# make submission
sub = pd.read_csv(os.path.join(data_dir, 'sample_submission.csv'))
sub.TARGET = pred[:, 1]
sub.to_csv(os.path.join(subs_dir, 'sub01.csv'), index = False)